# 텐서조작

## 목표
- `Generating Tensor`: 텐서의 생성 및 다양한 타입을 텐서로 변환할 수 있다.
- `Reshaping Tensor`: 텐서의 모양을 변경하고 구현할 수 있다.
    - 데이터 전처리
    - 신경망 층 간 연결
    - Feature Engineering
- `Merging & Spliting Tensor`: 텐서를 합치거나 나누거나 할 수 있다.
    - 데이터 배치 처리
    - 다중 입력/출력 모델
    - 교차 검증 및 데이터 분할

## 목차
1. `텐서 이해하기`
    - 텐서를 생성하고 텐서로 변환하는 방법을 이해
    - 텐서에서의 indexing 이해
2. `텐서의 모양 바꾸기`
    - 텐서의 shape 을 바꾸는 여러가지 함수 이해
    - 텐서의 차원을 추가하거나 변경하는 방법에 대한 이해
    - 역할이 비슷한 함수들의 차이 이해
3. `텐서 합치기와 나누기`
    - 여러 텐서를 합치는 방법에 대한 이해
    - 하나의 텐서를 여러개로 나누는 방법에 대한 이해

In [1]:
import torch # PyTorch 불러오기
import numpy as np # numpy 불러오기
import warnings # 경고 문구 제거
warnings.filterwarnings('ignore')

## 1. 텐서 이해하기

### 1-1 텐서를 생성하고 변환하는 방법을 이해
> Random 값을 갖는 텐서를 생성하고, list 나 numpy array 같은 다양한 형태의 배열들을 Pytorch 를 이용하여 텐서로 변환하는 과정을 알아본다.

💡 텐서의 값을 무작위로 생성하는 방법:

- `rand`: 0과 1 사이의 균일한 분포(uniform Distribution)에서 무작위로 생성된 텐서를 반환
- `randn`: 평균이 0이고 표준편차가 1인 정규분포(Gaussian Distribution)에서 무작위로 생성된 텐서를 반환
- `randint`: 주어진 범위 내에서 정수값을 무작위로 선택하여 생성된 텐서를 반환 **(min <= values < max)**

📚 Reference: 
- `rand`: https://pytorch.org/docs/stable/generated/torch.rand.html
- `randn`: https://pytorch.org/docs/stable/generated/torch.randn.html
- `randont`: https://pytorch.org/docs/stable/generated/torch.randint.html

In [3]:
# N x M 텐서로 반환
print(torch.rand(2,3))
print(torch.randn(2,3))
print(torch.randint(1, 10, (2, 3))) # 생성가능한 최소값 1, 최대값 9

tensor([[0.4784, 0.4023, 0.9215],
        [0.8415, 0.4990, 0.7861]])
tensor([[-1.8215,  0.6000, -1.0479],
        [-0.0432, -2.2551,  2.0587]])
tensor([[5, 5, 3],
        [8, 3, 6]])


💡 텐서의 값을 지정해서 생성하는 방법:
* `zeros` : 모든 요소가 0인 텐서 반환
* `ones`: 모든 요소가 1인 텐서 반환
* `full`: 모든 요소가 지정된 값인 텐서 반환
* `eye`: 단위 행렬 반환 (**대각선 요소가 1**이고 나머지 요소가 0인 행렬)


📚 Reference: 
* `zeros` https://pytorch.org/docs/stable/generated/torch.zeros.html
* `ones` https://pytorch.org/docs/stable/generated/torch.ones.html
* `full` https://pytorch.org/docs/stable/generated/torch.full.html
* `eye` https://pytorch.org/docs/stable/generated/torch.eye.html

In [4]:
# torch.zeros(*size) -> "," 로 구분하여 차원을 여러개로 늘릴 수 있다.
torch.zeros(3, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [5]:
# torch.zeros(*size) 
torch.ones(2, 2, 2)

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

In [6]:
# torch.full((size), value)
torch.full((2, 3), 5)

tensor([[5, 5, 5],
        [5, 5, 5]])

In [7]:
# 단위행렬 특성 상 정사각행렬(square matrix)만 가능
torch.eye(4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

💡 다양한 데이터를 텐서 형식으로 변환:
* `tensor` : 주어진 데이터를 텐서로 변환. 데이터는 list, tuple, numpy array 등의 형태일 수 있다.
* `from_numpy`: numpy array 를 텐서로 변환


📚 Reference: 
* `tensor` https://pytorch.org/docs/stable/generated/torch.tensor.html
* `from_numpy` https://pytorch.org/docs/stable/generated/torch.from_numpy.html

In [8]:
# list, tuple, numpy array 를 텐서로 바꾸기
ls = [[1,2,3,4,5], [6,7,8,9,10]]
tup = (1,2,3)
arr = np.array([[[1,2,3], [4,5,6,]], [[7,8,9], [10,11,12]]])

print(torch.tensor(ls))
print('\n')
print(torch.tensor(tup))
print('\n')
print(torch.tensor(arr))

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])


tensor([1, 2, 3])


tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]], dtype=torch.int32)


In [9]:
# array to tensor
torch.from_numpy(arr)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]], dtype=torch.int32)

💡 다양한 형식의 텐서 변환:
* `as_tensor` : 변환 전 데이터와의 메모리 공유(memory sharing)를 사용하여, 변환 전 데이터 변경 시 변환되어있는 텐서에서도 반영됨
* `Tensor`: float32 type 으로 텐서 변환


📚 Reference: 
* [as_tensor] https://pytorch.org/docs/stable/generated/torch.as_tensor.html
* [Tensor] https://pytorch.org/docs/stable/tensors.html

In [10]:
# torch.tensor 와 torch.as_tensor 의 차이점 알아보기
print('torch.tensor')
d1 = np.array([1,2,3,4,5])
tensor1 = torch.tensor(d1)
d1[0] = 10
print(tensor1) # 원본 데이터의 값 변경에 영향을 받지 않음

print('-------'*5)

print('torch.as_tensor')
d2 = np.array([1,2,3,4,5])
tensor1 = torch.as_tensor(d1) # 메모리 공유
d2[0] = 10
print(tensor1) # 원본 데이터의 값 변경에 영향을 받음

torch.tensor
tensor([1, 2, 3, 4, 5], dtype=torch.int32)
-----------------------------------
torch.as_tensor
tensor([10,  2,  3,  4,  5], dtype=torch.int32)


In [12]:
data = [1,2,3,4,5]
tensor1 = torch.tensor(data)
print('torch.tensor')
print("Output:", tensor1)
print("Type", tensor1.dtype) # 원본의 데이터 타입을 그대로 변환

tensor2 = torch.Tensor(data)
print('torch.Tensor')
print("Output:", tensor2)
print("Type", tensor2.dtype) # float32 타입의 Tensor 로 변환

torch.tensor
Output: tensor([1, 2, 3, 4, 5])
Type torch.int64
torch.Tensor
Output: tensor([1., 2., 3., 4., 5.])
Type torch.float32


### 1-2 텐서에서 Indexing 을 이해
> Indexing 개념과 Indexing 을 통해 값을 변경하는 방법에 대해 이해한다.
- Indexing 은 텐서 내의 특정 **요소**에 index를 통해 접근할 수 있는 방법을 의미한다.

💡 Indexing 이란?:
- `Indexing 기본`: **대괄호("[]")**를 통해 이루어지며, **":"** 는 특정 범위의 접근을 의미한다.
- `index_select`: 선택한 차원에서 인덱스에 해당하는 요소만을 추출하는 함수
- `masking 을 이용한 Indexing`: 조건에 맞는 요소들만 반환하는 방법
- `masked_select`: 주어진 mask에 해당하는 요소들을 추출하여 1차원으로 펼친 새로운 텐서를 반환하는 함수
- `take`: 주어진 인덱스를 사용하여 텐서에서 요소를 선택하는 함수. 인덱스 번호는 텐서를 1차원으로 늘려졌을 때 기준으로 접근해야한다.
- `gather`: 주어진 차원에서 인덱스에 해당하는 요소들을 선택하여 새로운 텐서를 반환


📚 Reference: 
* [Tensor indexing] : https://pytorch.org/cppdocs/notes/tensor_indexing.html
* [index_select] : https://pytorch.org/docs/stable/generated/torch.index_select.html
* [masked_select] : https://pytorch.org/docs/stable/generated/torch.masked_select.html
* [take] : https://pytorch.org/docs/stable/generated/torch.take.html
* [gather] : https://pytorch.org/docs/stable/generated/torch.gather.html

In [16]:
# 1차원 텐서에서 Indexing
tmp_1dim = torch.tensor([i for i in range(10)]) # 0~9 의 값을 갖는 1차원 텐서 생성

print(tmp_1dim[0])
print(tmp_1dim[-1])
print(tmp_1dim[2:4])

tensor(0)
tensor(9)
tensor([2, 3])


In [22]:
# n 차원 텐서 Indexing
tmp_3dim = torch.randint(0, 10, (4,3,2)) # 4채널, 3행, 2열
print("Shape: ", tmp_3dim.shape)
print(tmp_3dim)

print('-------'*8)

# 전체 채널과 전체 행에서 0번째 열만 추출
print(tmp_3dim[:,:,0].shape)
print(tmp_3dim[:,:,0])

print('\n')

# 0번째 채널의 전체 행에서 1번째 열만 추출
print(tmp_3dim[0,:,1].shape)
print(tmp_3dim[0,:,1])


Shape:  torch.Size([4, 3, 2])
tensor([[[0, 3],
         [5, 7],
         [0, 6]],

        [[8, 5],
         [2, 0],
         [7, 9]],

        [[3, 1],
         [8, 1],
         [3, 3]],

        [[9, 4],
         [3, 4],
         [5, 7]]])
--------------------------------------------------------
torch.Size([4, 3])
tensor([[0, 5, 0],
        [8, 2, 7],
        [3, 8, 3],
        [9, 3, 5]])


torch.Size([3])
tensor([3, 7, 6])


In [32]:
# index_select
# 열을 기준으로 0열과 2열을 추출
tmp_2dim = torch.randint(0, 10, (3, 4))
print(tmp_2dim)

print('\n')

my_index = torch.tensor([0, 2]) # 선택하고자 하는 index 는 텐서 형태이어야함.
print(torch.index_select(tmp_2dim, dim=1, index=my_index)) # 열추출
print('\n')
print(torch.index_select(tmp_2dim, dim=0, index=my_index)) # 행추출

tensor([[4, 6, 5, 2],
        [3, 9, 2, 6],
        [8, 2, 6, 6]])


tensor([[4, 5],
        [3, 2],
        [8, 6]])


tensor([[4, 6, 5, 2],
        [8, 2, 6, 6]])


In [33]:
# mask 를 이용한 텐서 Indexing (조건에 맞는 값만 추출)
mask = tmp_2dim >= 5 # 5보다 큰 텐서만 추출
tmp_2dim[mask] # 1차원 Tensor 로 반환

tensor([6, 5, 9, 6, 8, 6, 6])

In [34]:
# masked_select
torch.masked_select(tmp_2dim, mask=mask) # tmp_2dim[tmp_2dim >= 5] 와 동일

tensor([6, 5, 9, 6, 8, 6, 6])

In [36]:
# take
# Tensor 가 1차원으로 늘려졌을 때 기준으로 index 번호로 접근
tem_2dim = torch.tensor([[i for i in range(10)], [i for i in range(10, 20)]])
print(tem_2dim)
print('\n')
idx = torch.tensor([0, 5, 10, 15])
torch.take(tem_2dim, index=idx)

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])




tensor([ 0,  5, 10, 15])

In [41]:
# gather
# 행 또는 열의 index 를 각각(모두) 설정한다.
gather_idx = torch.tensor([[0, 1], [5,8]]) 
torch.gather(tem_2dim, dim=1, index=gather_idx)
# dim=1 을 기준으로 첫 행의 0, 1 번째, 두 번째 행의 5, 8 번째 indexing

tensor([[ 0,  1],
        [15, 18]])

## 2. 텐서의 모양 바꾸기

### 2-1. 텐서의 shape 을 바꾸는 여러가지 함수 이해
> 텐서의 모양을 자유자재로 바꾸는 방법에 대해 알아본다.

💡 텐서의 shape 변경:
> 텐서에 대한 모양을 변경할 때 **텐서의 크기(요소의 개수)가 유지되어야 한다**
* `size`: 텐서의 모양을 확인한다.
* `reshape`: 텐서의 모양을 변경한다. (메모리를 공유하지 않는다)
* `view`: 텐서의 모양을 변경한다.
* `transpose`: 텐서의 차원을 전치한다.
* `permute`: 텐서의 차원의 순서를 재배열한다.

📚 Reference: 
* [size] : https://pytorch.org/docs/stable/generated/torch.Tensor.size.html
* [reshape] : https://pytorch.org/docs/stable/generated/torch.reshape.html
* [view] : https://pytorch.org/docs/stable/generated/torch.Tensor.view.html
* [transpose] : https://pytorch.org/docs/stable/generated/torch.transpose.html
* [permute] : https://pytorch.org/docs/stable/generated/torch.permute.html

In [44]:
# size, # shape
print(torch.randn(2, 3, 5).size())
print(torch.randn(2, 3, 5).shape)

torch.Size([2, 3, 5])
torch.Size([2, 3, 5])


In [48]:
# 모양 변경 - reshape & view
a = torch.randn(2, 3, 5)
print(a)
print("Shape: ", a.size())
print('\n')

# 2 * 3 * 5 = 30
reshape_a = a.reshape(5, 6) # 3 차원 텐서를 2차원 텐서로 크기 변경
print(reshape_a)
print("Shape: ", reshape_a.size())
print('\n')

view_a = a.view(5, 6) # 3 차원 텐서를 2차원 텐서로 크기 변경
print(view_a)
print("Shape: ", view_a.size())


tensor([[[ 0.9311, -0.7279,  0.1766,  0.1792,  0.1511],
         [ 2.1681,  0.6011,  0.5407, -0.5879, -0.8650],
         [ 0.8555, -0.0207,  0.5178, -1.2998,  0.2312]],

        [[ 0.1731,  0.4273, -0.7035,  1.0637, -1.7200],
         [-1.2022,  1.0715, -1.4845, -0.4681, -0.9905],
         [-0.2045,  2.1790,  2.0393, -1.5453, -0.0882]]])
Shape:  torch.Size([2, 3, 5])


tensor([[ 0.9311, -0.7279,  0.1766,  0.1792,  0.1511,  2.1681],
        [ 0.6011,  0.5407, -0.5879, -0.8650,  0.8555, -0.0207],
        [ 0.5178, -1.2998,  0.2312,  0.1731,  0.4273, -0.7035],
        [ 1.0637, -1.7200, -1.2022,  1.0715, -1.4845, -0.4681],
        [-0.9905, -0.2045,  2.1790,  2.0393, -1.5453, -0.0882]])
Shape:  torch.Size([5, 6])


tensor([[ 0.9311, -0.7279,  0.1766,  0.1792,  0.1511,  2.1681],
        [ 0.6011,  0.5407, -0.5879, -0.8650,  0.8555, -0.0207],
        [ 0.5178, -1.2998,  0.2312,  0.1731,  0.4273, -0.7035],
        [ 1.0637, -1.7200, -1.2022,  1.0715, -1.4845, -0.4681],
        [-0.9905, -0.2

In [46]:
# -1 로 모양 자동 설정 
reshape_auto_a = a.reshape(3, -1)
reshape_auto_a.shape

torch.Size([3, 10])

In [49]:
tensor_a = torch.randint(1, 10, (3, 2, 5))
print(tensor_a)
print("Shape: ", tensor_a.size())
print('\n')

# transpose(전치) -> 서로 전치할 차원 2개를 지정
trans_tensor_a = tensor_a.transpose(1, 2) # (3, 2, 5) -> (3, 5, 2)
print(trans_tensor_a)
print("Shape: ", trans_tensor_a.size())
print('\n')

tensor([[[5, 7, 7, 1, 1],
         [6, 8, 6, 5, 3]],

        [[9, 5, 4, 1, 9],
         [1, 6, 7, 5, 8]],

        [[3, 1, 6, 8, 9],
         [9, 3, 1, 3, 3]]])
Shape:  torch.Size([3, 2, 5])


tensor([[[5, 6],
         [7, 8],
         [7, 6],
         [1, 5],
         [1, 3]],

        [[9, 1],
         [5, 6],
         [4, 7],
         [1, 5],
         [9, 8]],

        [[3, 9],
         [1, 3],
         [6, 1],
         [8, 3],
         [9, 3]]])
Shape:  torch.Size([3, 5, 2])




In [51]:
# permute - shape 변경
print(tensor_a)
print("Shape: ", tensor_a.size())
print('\n')

permute_a = tensor_a.permute(0, 2, 1) # (3, 2, 5) -> (3, 5, 2)
print(permute_a)
print("Shape: ", permute_a.size())


tensor([[[5, 7, 7, 1, 1],
         [6, 8, 6, 5, 3]],

        [[9, 5, 4, 1, 9],
         [1, 6, 7, 5, 8]],

        [[3, 1, 6, 8, 9],
         [9, 3, 1, 3, 3]]])
Shape:  torch.Size([3, 2, 5])


tensor([[[5, 6],
         [7, 8],
         [7, 6],
         [1, 5],
         [1, 3]],

        [[9, 1],
         [5, 6],
         [4, 7],
         [1, 5],
         [9, 8]],

        [[3, 9],
         [1, 3],
         [6, 1],
         [8, 3],
         [9, 3]]])
Shape:  torch.Size([3, 5, 2])


### 2-2. 텐서의 차원을 추가하거나 변경하는 방법에 대한 이해
> 텐서의 차원 변경 방식에 대한 이해와 활용

💡 텐서의 차원을 추가하거나 변경하는 방법에 대한 이해 및 실습:
- `unsqueeze`: 텐서에 특정 차원에 크기가 1인 차원을 추가한다.
- `squeeze`: 텐서에 차원의 크기가 1인 차원을 제거한다.
- `expand`: 텐서의 값을 반복하여 크기를 확장.
    - **A 텐서가 1차원일 경우**: A 텐서의 크기가 (m,) 이면 m 은 고정하고 (x, m)의 크기로만 확장가능
    - **A 텐서가 2차원 이상일 경우**: 크기가 1인 차원에 대해서만 적용가능. A 텐서의 크기가 (1, m)이면 (x, m), (m, 1) 이면 (x, y)로만 가능
- `repeat`: 텐서를 반복하여 크기를 확장
    - e.g. A 텐서가 (m,n) 크기를 가진다하고, A 텐서를 repeat(i, j)를 하면 결과 값으로 (m x i, n x j) 크기의 텐서가 생성됨.
- `flatten`: 다차원 텐서를 1차원 텐서로 변경
- `ravel`: 다차원 텐서를 1차원 텐서로 변경

📚 Reference: 
* [unsqueeze] : https://pytorch.org/docs/stable/generated/torch.unsqueeze.html
* [squeeze] : https://pytorch.org/docs/stable/generated/torch.squeeze.html
* [expand] : https://pytorch.org/docs/stable/generated/torch.Tensor.expand.html
* [repeat] : https://pytorch.org/docs/stable/generated/torch.Tensor.repeat.html
* [flatten] : https://pytorch.org/docs/stable/generated/torch.flatten.html
* [ravel] : https://pytorch.org/docs/stable/generated/torch.ravel.html